// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WIlliGram.Models;

namespace WIlliGram.Migrations
{
    [DbContext(typeof(WIlliGramContext))]
    partial class WIlliGramContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WIlliGram.Models.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FriendsSince");

                    b.Property<string>("Job");

                    b.Property<string>("Name");

                    b.Property<string>("Portrait");

                    b.HasKey("Id");

                    b.ToTable("Friend");
                });

            modelBuilder.Entity("WIlliGram.Models.Witter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Blah");

                    b.Property<int>("Likes");

                    b.Property<DateTime>("WroteDate");

                    b.HasKey("Id");

                    b.ToTable("Witter");
                });
#pragma warning restore 612, 618
        }
    }
}
